# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1550a7c1023d83b53e7caad1c64e19244a7915692f834289de5cc831971b9fa3c47325795638ce264102a57359ab49536bc23bfb8aec789faa84e8015c9daae
  stripe_publishable_key: pk_test_bWZYpne0zFUpkhi4J9Dn8hUz
  stripe_secret_key: sk_test_ltKVFwSNKRG7WB5z0SNG8myQ

test:
  secret_key_base: a375d4bddd19a8cb3f372189d0cdbc64721aa15bb35d546ebb8fb370dc0bf9c96ac1d3b62ab2fb5ad73ce65d3a2d9fba9bf952a277f826714aa6b55ab3621304

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: <%= ENV['stripe_publishable_key'] %>
  stripe_secret_key: <%= ENV['stripe_publishable_key'] %>
